config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'excuses/index'
  root to: "excuses#index"

  # post "bookmarks/:excuse_id/create" => "bookmarks#create"
  # post "bookmarks/:excuse_id/create", to: "bookmarks#create"
  # get "excuses/:excuse_id/edit", to: "excuses#edit"
  # post "bookmarks/:excuse_id/destroy" => "bookmarks#destroy"
  # post 'bookmarks/create'
  # post 'bookmarks/destroy'
  resources :excuses
  resources :excuses do
    resource :bookmarks, only: [:create, :destroy]
  end

end

app/models/age.rb
class Age < ActiveHash::Base
  self.data = [
    { id: 0, name: '--' },
    { id: 1, name: '10代' },
    { id: 2, name: '20代 前半' },
    { id: 3, name: '20代 後半' },
    { id: 4, name: '30代 前半' },
    { id: 5, name: '30代 後半' },
    { id: 6, name: '40代 前半' },
    { id: 7, name: '40代 後半' },
    { id: 8, name: '50代 前半' },
    { id: 9, name: '50代 後半' },
    { id: 10, name: '60代 前半' },
    { id: 11, name: '60代 後半' },
    { id: 12, name: '70代 前半' },
    { id: 13, name: '70代 後半' },
    { id: 14, name: '80代 前半' },
    { id: 15, name: '80代 後半' },
    { id: 16, name: '90代 前半' },
    { id: 17, name: '90代 後半' },
    { id: 18, name: '100代' },
    { id: 20, name: 'その他' }

  ]

  include ActiveHash::Associations
  has_many :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/behind_time.rb
class BehindTime < ActiveHash::Base

  self.data = [
    {id: 0, name: '--' },   {id: 1, name: '２〜３分'}, {id: 2, name: '5分'}, {id: 3, name: '10分'}, 
    {id: 4, name: '15分'},  {id: 5, name: '20分'}, {id: 6, name: '25分'}, {id: 7, name: '30分'},
    {id: 8, name: '35分'}, {id: 9, name: '40分'}, {id: 10, name: '45分'},
    {id: 11, name: '50分'}, {id: 12, name: '55分'}, {id: 13, name: '１時間'},
    {id: 14, name: '１時間10分'}, {id: 15, name: '１時間20分'}, {id: 16, name: '１時間30分'},
    {id: 17, name: '１時間40分'}, {id: 18, name: '１時間50分'}, {id: 19, name: '２時間'},
    {id: 20, name: '２時間30分'}, {id: 21, name: '３時間'}, {id: 22, name: '4時間'},
    {id: 23, name: '5時間'}, {id: 24, name: '6時間以上'}, {id: 25, name: '1日'},
    {id: 26, name: '2〜3日'}, {id: 27, name: '４〜5日'}, {id: 28, name: '１週間'},
    {id: 29, name: '１ヶ月以上'}, {id: 30, name: '２〜3ヶ月以上'}, {id: 31, name: '半年以上'}
    ]

    include ActiveHash::Associations
    has_many :excuses

end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :excuse

  validates_uniqueness_of :excuse_id, scope: :user_id
end

app/models/excuse.rb
class Excuse < ApplicationRecord
  belongs_to :user

  has_many :bookmarks, dependent: :destroy
  has_many :excuse_tag_relations
  has_many :tags, through: :excuse_tag_relations

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :behind_time


end

app/models/excuse_tag_relation.rb
class ExcuseTagRelation < ApplicationRecord

  belongs_to :excuse
  belongs_to :tag

end

app/models/excuses_tag.rb
class ExcusesTag

  include ActiveModel::Model
  attr_accessor :reason, :result, :behind_time_id, :name, :user_id

  with_options presence: true do
    validates :reason
    validates :result
  end

  def save
    excuse = Excuse.create(user_id: user_id, reason: reason, result: result, behind_time_id: behind_time_id)
    tag = Tag.create(name: name)

    ExcuseTagRelation.create(excuse_id: excuse.id, tag_id: tag.id)
  end

end

app/models/job.rb
class Job < ActiveHash::Base
  self.data = [
    { id: 0, name: '--' },
    { id: 1, name: '学生' },
    { id: 2, name: '金融／保険業' },
    { id: 3, name: '通信業' },
    { id: 4, name: '流通／小売業' },
    { id: 5, name: '運輸業' },
    { id: 6, name: '旅行業' },
    { id: 7, name: '電力／ガス／水道' },
    { id: 8, name: '製造業' },
    { id: 9, name: 'サービス業' },
    { id: 10, name: '医療／福祉' },
    { id: 11, name: '建設／不動産業' },
    { id: 12, name: '放送／出版／マスコミ' },
    { id: 13, name: '官公庁' },
    { id: 14, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :users

end

app/models/sex.rb
class Sex < ActiveHash::Base
  self.data = [
    { id: 0, name: '--' },
    { id: 1, name: '男性' },
    { id: 2, name: '女性' },
    { id: 3, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :users

end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :excuse_tag_relations
  has_many :excuses, through: :excuse_tag_relations

end

app/models/user.rb
class User < ApplicationRecord
  has_many :excuses, dependent: :destroy
  has_many :bookmarks, dependent: :destroy

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :sex
  belongs_to :age
  belongs_to :job


  def already_bookmark?(excuse)
    self.bookmarks.exists?(excuse_id: excuse.id)
  end
  
  #アカウント用画像
  has_one_attached :image

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth, :configure_permitted_parameters, if: :devise_controller?


 private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(
      :sign_up, keys: [:nickname, :email, :encrypted_password, :sex_id, :age_id, :job_id]
    )
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == 'admin' && password == '2222'
    end
  end
  
  

end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

 def create
  @bookmark = current_user.bookmarks.create(excuse_id: params[:excuse_id])
  # @bookmark.save
  redirect_back(fallback_location: root_path)
  # ("/excuses/#{params[:excuse_id]}")
 end

 def destroy
  @excuse = Excuse.find(params[:excuse_id])
  @bookmark = current_user.bookmarks.find_by(excuse_id: @excuse.id)
  @bookmark.destroy
  redirect_back(fallback_location: root_path)
  # ("/excuses/#{params[:excuse_id]}")
 end


end 

app/controllers/excuses_controller.rb
class ExcusesController < ApplicationController

  def index
    @excuse = Excuse.order("created_at DESC")
    @user = User.order("created_at DESC")
   #  order("created_at DESC")
  end

  def show
  end

  def new
    @excuse = ExcusesTag.new
  end

  def create
    @excuse = ExcusesTag.new(excuse_params)

   if @excuse.valid?
      @excuse.save
      return redirect_to root_path
   else
      render "new"
   end
  end

  private

  def excuse_params
     params.require(:excuses_tag).permit( :reason, :behind_time_id, :result, :name ).merge(user_id: current_user.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.includes(:excuses).find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/excuses_helper.rb
module ExcusesHelper
end

app/views/excuses/_excuse.html.erb
    <% if user_signed_in? %>
<script src="copy.js"></script>
 <div class="card" >
 <ul class='excuse-lists'> 
      <% @excuse.each do |excuse| %>  
    <li class='list' >

     <div class="box26">
      <span class="box-title">
        <%= "#{current_user.nickname}" %> 
        <%= "#{current_user.age.name}" %>
        <%= "#{current_user.sex.name}" %>
        <%= "#{current_user.job.name}" %>
      </span>
       <%# 本文の記述 %> 
      <div class="excuse_text">
        <%= "#{excuse.reason}"  "#{excuse.behind_time.name}" "#{excuse.result}" %>      
        <button class="copy_excuse__btn">コピー</button>
     </div> 
     <div class="copy_excuse__btn">   
       <% if current_user.already_bookmark?(excuse) %>
       <%= link_to 'お気に入りから外す', excuse_bookmarks_path(excuse), method: :delete %>
       <% else %>
       <%= link_to 'お気に入り', excuse_bookmarks_path(excuse), method: :post %>
       <% end %>
       <%= excuse.bookmarks.count %>
     </div>
    </li>
   <% end %>
 </ul>
</div>

<% end %>
        <%# </div>
        <div class='item-info'>
          <h3 class='item-name'>
            <%= item.item_name %>
          <%# </h3>
          <div class='item-price'>
            <%# <span><%= item.price円<br><%= item.charge.name</span> %>
            <%# <div class='star-btn'>
              <%= image_tag "star.png", class:"star-icon" %>
              <%# <span class='star-count'>0</span>
            </div> %> 
          <%# </div>
        </div>
        <% end %>
      <%# </li>
     <% end %>

app/views/excuses/_form.html.erb
<%= form_with model: @excuse, url: excuses_path, local: true do |f|%>

  <div class="field">
    <%= f.label :reason, "理由" %><br />
    <%= f.text_field :reason, id:"excuse_reason" %>
  </div>

  <div class="field">
    <%= f.label :behind_time_id, "期間" %><br />
    <%= f.collection_select(:behind_time_id, BehindTime.all, :id, :name, {}, {class:"select-box", id:"excuse_time"}) %> 
  </div>

  <div class="field">
    <%= f.label :result, "結果" %><br />
    <%= f.text_field :result, id:"excuse_result" %>
  </div>

   <div class="tag-field", id='tag-field'>
    <%= f.label :name, "タグ" %><br />
    <%= f.text_field :name, id:"excuse_tag" %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/excuses/index.html.erb
<main class="main">
  <div class="inner">
   <%= link_to image_tag("title_logo.png", class: :title_logo), root_path %>
  </div>
 

  <div class="inner2">
      <%= link_to "遅刻します", root_path, class: :excuse__btn %>
    <% if user_signed_in? %> 
      <%= link_to "いいわけ作成", new_excuse_path, class: :excuse__btn %>
      <%= link_to "お気に入り", root_path, class: :excuse__btn %>
    <% end %>  
  </div>
  <div class="card__wrapper">
      <%# 言い訳一覧の表示 %>
      <%= render partial: "excuse", locals: { excuse: @excuse } %>
  </div>
</main> 

app/views/excuses/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">いいわけ投稿</h2>

        <%= render partial: "form", locals: { excuse: @excuse } %>
        
    </div>
  </div>
</div>

app/views/excuses/show.html.erb
<h1>test</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Iiwakemeikan</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("logo.png", class: :logo), root_path %>
          </div>

           <% if user_signed_in? %>           
            <div class="nav__right"> 
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__logout %>
            </div>         
           <% else %> 

            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
           <% end %> 

        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © IIWAKE MEIKAN All rights reserved.</p>
    </footer>
  </body>
</html>